export type LocationRecord = {
  locationId: string;
  locationName: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  county: string;
  state: string;
  zip: string;
  externalIdentifier: string;
  active: boolean;
};

export type StateOption = {
  abbreviation: string;
  name: string;
  label: string;
};

export const STATES: StateOption[] = [
  { abbreviation: 'AZ', name: 'Arizona', label: 'AZ - Arizona' },
  { abbreviation: 'AL', name: 'Alabama', label: 'AL - Alabama' },
  { abbreviation: 'AK', name: 'Alaska', label: 'AK - Alaska' },
  { abbreviation: 'AR', name: 'Arkansas', label: 'AR - Arkansas' },
  { abbreviation: 'CA', name: 'California', label: 'CA - California' },
  { abbreviation: 'CO', name: 'Colorado', label: 'CO - Colorado' },
  { abbreviation: 'CT', name: 'Connecticut', label: 'CT - Connecticut' },
  { abbreviation: 'DE', name: 'Delaware', label: 'DE - Delaware' },
  { abbreviation: 'FL', name: 'Florida', label: 'FL - Florida' },
  { abbreviation: 'GA', name: 'Georgia', label: 'GA - Georgia' },
  { abbreviation: 'HI', name: 'Hawaii', label: 'HI - Hawaii' },
  { abbreviation: 'IA', name: 'Iowa', label: 'IA - Iowa' },
  { abbreviation: 'ID', name: 'Idaho', label: 'ID - Idaho' },
  { abbreviation: 'IL', name: 'Illinois', label: 'IL - Illinois' },
  { abbreviation: 'IN', name: 'Indiana', label: 'IN - Indiana' },
  { abbreviation: 'KS', name: 'Kansas', label: 'KS - Kansas' },
  { abbreviation: 'KY', name: 'Kentucky', label: 'KY - Kentucky' },
  { abbreviation: 'LA', name: 'Louisiana', label: 'LA - Louisiana' },
  { abbreviation: 'MA', name: 'Massachusetts', label: 'MA - Massachusetts' },
  { abbreviation: 'MD', name: 'Maryland', label: 'MD - Maryland' },
  { abbreviation: 'ME', name: 'Maine', label: 'ME - Maine' },
  { abbreviation: 'MI', name: 'Michigan', label: 'MI - Michigan' },
  { abbreviation: 'MN', name: 'Minnesota', label: 'MN - Minnesota' },
  { abbreviation: 'MO', name: 'Missouri', label: 'MO - Missouri' },
  { abbreviation: 'MS', name: 'Mississippi', label: 'MS - Mississippi' },
  { abbreviation: 'MT', name: 'Montana', label: 'MT - Montana' },
  { abbreviation: 'NC', name: 'North Carolina', label: 'NC - North Carolina' },
  { abbreviation: 'ND', name: 'North Dakota', label: 'ND - North Dakota' },
  { abbreviation: 'NE', name: 'Nebraska', label: 'NE - Nebraska' },
  { abbreviation: 'NH', name: 'New Hampshire', label: 'NH - New Hampshire' },
  { abbreviation: 'NJ', name: 'New Jersey', label: 'NJ - New Jersey' },
  { abbreviation: 'NM', name: 'New Mexico', label: 'NM - New Mexico' },
  { abbreviation: 'NV', name: 'Nevada', label: 'NV - Nevada' },
  { abbreviation: 'NY', name: 'New York', label: 'NY - New York' },
  { abbreviation: 'OH', name: 'Ohio', label: 'OH - Ohio' },
  { abbreviation: 'OK', name: 'Oklahoma', label: 'OK - Oklahoma' },
  { abbreviation: 'OR', name: 'Oregon', label: 'OR - Oregon' },
  { abbreviation: 'PA', name: 'Pennsylvania', label: 'PA - Pennsylvania' },
  { abbreviation: 'RI', name: 'Rhode Island', label: 'RI - Rhode Island' },
  { abbreviation: 'SC', name: 'South Carolina', label: 'SC - South Carolina' },
  { abbreviation: 'SD', name: 'South Dakota', label: 'SD - South Dakota' },
  { abbreviation: 'TN', name: 'Tennessee', label: 'TN - Tennessee' },
  { abbreviation: 'TX', name: 'Texas', label: 'TX - Texas' },
  { abbreviation: 'UT', name: 'Utah', label: 'UT - Utah' },
  { abbreviation: 'VA', name: 'Virginia', label: 'VA - Virginia' },
  { abbreviation: 'VT', name: 'Vermont', label: 'VT - Vermont' },
  { abbreviation: 'WA', name: 'Washington', label: 'WA - Washington' },
  { abbreviation: 'WI', name: 'Wisconsin', label: 'WI - Wisconsin' },
  { abbreviation: 'WV', name: 'West Virginia', label: 'WV - West Virginia' },
  { abbreviation: 'WY', name: 'Wyoming', label: 'WY - Wyoming' },
];

export const ARIZONA_COUNTIES: string[] = [
  'Apache',
  'Cochise',
  'Coconino',
  'Gila',
  'Graham',
  'Greenlee',
  'La Paz',
  'Maricopa',
  'Mohave',
  'Navajo',
  'Pima',
  'Pinal',
  'Santa Cruz',
  'Yavapai',
  'Yuma',
];

export const LOCATIONS: LocationRecord[] = [
  {
    locationId: 'location-1',
    locationName: 'Austin Assessment Center',
    addressLine1: '1201 West 5th Street',
    addressLine2: 'Suite 210',
    city: 'Austin',
    county: 'Travis',
    state: 'TX',
    zip: '78703',
    externalIdentifier: 'LOC-001',
    active: true,
  },
  {
    locationId: 'location-2',
    locationName: 'Bexar Field Office',
    addressLine1: '3400 North Loop 1604 West',
    addressLine2: 'Building B',
    city: 'San Antonio',
    county: 'Bexar',
    state: 'TX',
    zip: '78257',
    externalIdentifier: 'LOC-002',
    active: true,
  },
  {
    locationId: 'location-3',
    locationName: 'Collin Regional Site',
    addressLine1: '7700 Preston Road',
    addressLine2: '',
    city: 'Plano',
    county: 'Collin',
    state: 'TX',
    zip: '75024',
    externalIdentifier: 'LOC-003',
    active: true,
  },
  {
    locationId: 'location-4',
    locationName: 'Dallas Metro Hub',
    addressLine1: '1901 Main Street',
    addressLine2: 'Floor 9',
    city: 'Dallas',
    county: 'Dallas',
    state: 'TX',
    zip: '75201',
    externalIdentifier: 'LOC-004',
    active: true,
  },
  {
    locationId: 'location-5',
    locationName: 'El Paso Operations Office',
    addressLine1: '500 North Stanton Street',
    addressLine2: 'Suite 420',
    city: 'El Paso',
    county: 'El Paso',
    state: 'TX',
    zip: '79901',
    externalIdentifier: 'LOC-005',
    active: false,
  },
  {
    locationId: 'location-6',
    locationName: 'Fort Worth North Site',
    addressLine1: '6200 Camp Bowie Boulevard',
    addressLine2: '',
    city: 'Fort Worth',
    county: 'Tarrant',
    state: 'TX',
    zip: '76116',
    externalIdentifier: 'LOC-006',
    active: true,
  },
  {
    locationId: 'location-7',
    locationName: 'Galveston Harbor Office',
    addressLine1: '801 25th Street',
    addressLine2: '',
    city: 'Galveston',
    county: 'Galveston',
    state: 'TX',
    zip: '77550',
    externalIdentifier: 'LOC-007',
    active: true,
  },
  {
    locationId: 'location-8',
    locationName: 'Harris Central Campus',
    addressLine1: '1515 Fannin Street',
    addressLine2: 'Suite 300',
    city: 'Houston',
    county: 'Harris',
    state: 'TX',
    zip: '77002',
    externalIdentifier: 'LOC-008',
    active: true,
  },
  {
    locationId: 'location-9',
    locationName: 'Lubbock Plains Office',
    addressLine1: '1120 Texas Avenue',
    addressLine2: '',
    city: 'Lubbock',
    county: 'Lubbock',
    state: 'TX',
    zip: '79401',
    externalIdentifier: 'LOC-009',
    active: false,
  },
  {
    locationId: 'location-10',
    locationName: 'Nueces Gulf Branch',
    addressLine1: '410 Shoreline Boulevard',
    addressLine2: 'Unit 5',
    city: 'Corpus Christi',
    county: 'Nueces',
    state: 'TX',
    zip: '78401',
    externalIdentifier: 'LOC-010',
    active: true,
  },
  {
    locationId: 'location-11',
    locationName: 'Tarrant South Office',
    addressLine1: '4200 South Freeway',
    addressLine2: '',
    city: 'Fort Worth',
    county: 'Tarrant',
    state: 'TX',
    zip: '76115',
    externalIdentifier: 'LOC-011',
    active: true,
  },
  {
    locationId: 'location-12',
    locationName: 'Williamson District Annex',
    addressLine1: '300 University Boulevard',
    addressLine2: 'Suite 120',
    city: 'Round Rock',
    county: 'Williamson',
    state: 'TX',
    zip: '78665',
    externalIdentifier: 'LOC-012',
    active: true,
  },
];
